// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQyyclSy-0VTAEbbjggUhsW4jYsoIxE8Y',
    appId: '1:511352446547:web:7722e5e332a735c73bb0a6',
    messagingSenderId: '511352446547',
    projectId: 'urban-patrol-652af',
    authDomain: 'urban-patrol-652af.firebaseapp.com',
    storageBucket: 'urban-patrol-652af.firebasestorage.app',
    measurementId: 'G-7GGDKK8W8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfeXAoNIkBah9MAcPqPB1i1pHriaXuR2w',
    appId: '1:511352446547:android:7ed130d293b5ebb43bb0a6',
    messagingSenderId: '511352446547',
    projectId: 'urban-patrol-652af',
    storageBucket: 'urban-patrol-652af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKVeuxV0Skxp8-fKrslxviO57ye3vhPrY',
    appId: '1:511352446547:ios:6c98b4f40f2444db3bb0a6',
    messagingSenderId: '511352446547',
    projectId: 'urban-patrol-652af',
    storageBucket: 'urban-patrol-652af.firebasestorage.app',
    iosBundleId: 'com.example.urbanPatrolBtl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKVeuxV0Skxp8-fKrslxviO57ye3vhPrY',
    appId: '1:511352446547:ios:6c98b4f40f2444db3bb0a6',
    messagingSenderId: '511352446547',
    projectId: 'urban-patrol-652af',
    storageBucket: 'urban-patrol-652af.firebasestorage.app',
    iosBundleId: 'com.example.urbanPatrolBtl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQyyclSy-0VTAEbbjggUhsW4jYsoIxE8Y',
    appId: '1:511352446547:web:da7211e3b5d7e6bb3bb0a6',
    messagingSenderId: '511352446547',
    projectId: 'urban-patrol-652af',
    authDomain: 'urban-patrol-652af.firebaseapp.com',
    storageBucket: 'urban-patrol-652af.firebasestorage.app',
    measurementId: 'G-LV0MRWVL85',
  );
}
